version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.2
    - 13.0.3
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: snyk
    versions:
    - 1.507.0
    - 1.512.0
    - 1.513.0
    - 1.555.0
    - 1.557.0
    - 1.559.0
    - 1.560.0
    - 1.561.0
    - 1.570.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 15.0.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: three
    versions:
    - 0.125.0
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
